sudo: required
services:
  - docker

before_install:
  - docker build -t lexworks/docker-react -f Dockerfile.dev .

script:
  - docker run lexworks/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "uniapp"
  env: "Uniapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-883287720091"
  bucket_path: "uniapp"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

